name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build arm64 test containers
        run: |
          cp -R base/template_configs configs
          cp base/template_configs/wifi/psks.json configs/wifi/
          ./build_docker_compose.sh
      -
        name: Build frontend
        run: |
          docker build frontend -t super_frontend
      -
        name: Authenticate to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      -
        name: Push images
        env: 
          CONTAINERS: api base dhcp dhcp_client dns frontend multicast_udp_proxy ppp wifid wireguard
        run: |
          for C in $CONTAINERS; do
            docker tag super_api ghcr.io/spr-networks/super_${C}:latest
            docker push ghcr.io/spr-networks/super_${C}:latest
          done
