name: Docker Image AMD64 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Authenticate to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: Build amd64 test containers
        run: |
          cp -R base/template_configs configs
          export DOCKER_DEFAULT_PLATFORM=linux/amd64
          ./build_docker_compose.sh
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
